url: https://phscrc.com
baseurl:

# Site settings
title: PHSCRC
email: phscrc@gmail.com
description: "Princeton High School Computer and Robotics Club"


# Team names, titles and social links
alumni:
- name: Gota Nakamura
  pic: 3
  occupation: Engineering student at WPI
  quote: "I think CRC really is a great opportunity for people interested in programming and circuits. That kind of opportunity isn't common in most schools. So I think it's good for students like me!"
# - name: Lachlan McCarty
#   pic: 3
#   occupation: student at Princeton
#   quote: Howdy
# - name: Aaron Olkin
#   pic: 3
#   occupation: student at Harvard
#   quote: Howdy
# - name: Jacob Van Buren
#   pic: 3
#   occupation: Software developer at Jane St.
#   quote: Howdy

people:
- name: Lincoln Roth
  pic: 1
  position: President
  social:
    - title: github
      url: "https://github.com/lincolnmroth"
    - title: envelope
      url: "mailto://lincolnmroth@gmail.com"
    - title: link
      url: "http://lincolnroth.com"

- name: Charlie Luo
  pic: 3
  position: Vice-President
  social:
    - title: github
      url: #
    - title: envelope
      url: #
    - title: link
      url: #

- name: Joann Shi
  pic: 3
  position: Financial Manager
  social:
    - title: github
      url: #
    - title: envelope
      url: #
    - title: link
      url: #
- name: Aditya Prasad
  pic: 3
  position: Logistics Manager
  social:
    - title: github
      url: #
    - title: envelope
      url: #
    - title: link
      url: #
# - name: Coming soon!
#   pic: 3
#   position: Outreach Manager
#   social:
#     - title: github
#       url: #
#     - title: envelope
#       url: #
#     - title: link
#       url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/PHSCRC
  - title: facebook
    url: https://www.facebook.com/groups/PHSCRC/
  - title: github
    url: http://github.com/PHSCRC

# Postal address (add as many lines as necessary)
address:
  - line: 151 Moore St.
  - line: Princeton NJ, 08540

# Build settings
markdown: kramdown
permalink: pretty
